version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    container_name: handler
    volumes:
      - ./sibdev:/app
    ports:
      - "8000:8000"
    env_file:
      - sibdev/.env
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - sibdev/.env
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"

volumes:
  postgres_data: