[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
known_third_party = ["django", "rest_framework"]
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip_glob=["**/migrations/*"]
line_length = 120
atomic = true
lines_between_types = 0
lines_after_imports = 2
force_alphabetical_sort_within_sections = true

[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | migrations
)/
'''